---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.arr.sonarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'

- name: 'Converge | toggle SSL'
  hosts: 'sonarr-debian-13-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Converge | toggle SSL | apply r_pufky.arr.sonarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'
      vars:
        sonarr_cfg_enable_ssl: false
