---
###############################################################################
# Enable SSL
###############################################################################
# SSL is enabled and toggled correctly.
#
# Tests:
# * /data/sonarr/config/sonarr.pfx exists.
# * toggling ssl on, then off removes sonarr.pfx.
#   <EnableSsl>False</EnableSsl>  # true requires ssl_cert
#   <SslCertPath>/data/sonarr/config/snakeoil.pfx</SslCertPath>
#   <SslCertPassword>testing</SslCertPassword>  # stored plaintext.
# * sonarr_cfg_enable_ssl -- test when false w and w/o cert.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        sonarr_cfg_enable_ssl: true
        sonarr_cfg_ssl_cert_path: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/cache/test.pfx"
          }}'
        sonarr_cfg_ssl_cert_password: 'test'
        sonarr_srv_media_root_folders: ['/data/media']
        sonarr_cfg_api_key: 'abcdef1234567890abcdef1234567890'
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v4.0.16.2944'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/Sonarr.main.4.0.16.2944.linux-x64.tar.gz"
              }}'
          - comment: 'toggle'
            version: 'v4.0.16.2944'
            asset: '{{
                lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
                "/molecule/cache/Sonarr.main.4.0.16.2944.linux-x64.tar.gz"
              }}'
platforms:
  - name: 'sonarr-debian-13-enable_ssl'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'sonarr-debian-13-enable_ssl-toggle'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
