---
# yamllint disable rule:line-length
###############################################################################
# Prepare
###############################################################################
# Testing requires a valid PFX certificate. Generate a test certificate valid
# for 10 years (all default values, password: 'test'):
#
# Place in cache/test.pfx.
#
# Reference:
# * https://gist.github.com/rquackenbush/53ff432567699b21c86f3360fb4ec7f0
# * https://superuser.com/questions/226192/avoid-password-prompt-for-keys-and-prompts-for-dn-information
# yamllint enable rule:line-length

- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | generate cache location'
      ansible.builtin.set_fact:
        _test_cache:
          '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache'

    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | parse test version'
      ansible.builtin.set_fact:
        test_version: '4.0.15.2941'

    - name: '{{ "Prepare | cache " ~ test_version }}'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: '{{ "Prepare | cache " ~ test_version }}'
        test_dest: '{{ "Sonarr.main." ~ test_version ~ ".linux-x64.tar.gz" }}'
        test_url: '{{
            "https://github.com/Sonarr/Sonarr/releases/download/" ~
            "v" ~ test_version ~ "/" ~
            "Sonarr.main." ~ test_version ~ ".linux-x64.tar.gz"
          }}'
        test_mode: '0640'

    - name: 'Prepare | generate test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'req'
          - '-new'
          - '-newkey'
          - 'rsa:4096'
          - '-nodes'
          - '-subj'
          - '/C=US/ST=NY/L=NY/O=test/CN=test.example.com'
          - '-keyout'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.csr'
        creates: '{{ _test_cache }}/test.key'

    - name: 'Prepare | sign test certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'x509'
          - '-req'
          - '-sha256'
          - '-days'
          - '3650'
          - '-in'
          - '{{ _test_cache }}/test.csr'
          - '-signkey'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.pem'
        creates: '{{ _test_cache }}/test.pem'

    - name: 'Prepare | pack PFX certificate'
      ansible.builtin.command:
        argv:
          - 'openssl'
          - 'pkcs12'
          - '-export'
          - '-in'
          - '{{ _test_cache }}/test.pem'
          - '-inkey'
          - '{{ _test_cache }}/test.key'
          - '-out'
          - '{{ _test_cache }}/test.pfx'
          - '-passout'
          - 'pass:test'
        creates: '{{ _test_cache }}/test.pfx'
