---
- name: 'Verify | SSL enabled'
  hosts: 'sonarr-debian-13-enable_ssl'
  gather_facts: false
  tasks:
    - name: 'Verify | SSL enabled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | SSL enabled | config.xml'
        test_src: 'files/config_ssl.xml'
        test_file: '/data/sonarr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'
        test_diff: true

    - name: 'Verify | SSL enabled | /data/sonarr/config/sonarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | SSL enabled | /data/sonarr/config/sonarr.pfx'
        test_file: '/data/sonarr/config/sonarr.pfx'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0640'
        test_state: 'file'
        test_diff: true

- name: 'Verify | SSL toggled'
  hosts: 'sonarr-debian-13-enable_ssl-toggle'
  gather_facts: false
  tasks:
    - name: 'Verify | SSL toggled | config.xml'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | SSL toggled | config.xml'
        test_src: 'files/config_toggle.xml'
        test_file: '/data/sonarr/config/config.xml'
        test_owner: 'media'
        test_group: 'media'
        test_mode: '0600'
        test_diff: true

    - name: 'Verify | SSL toggled | /data/sonarr/config/sonarr.pfx'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'file.yml'
      vars:
        test_name: 'Verify | SSL toggled | /data/sonarr/config/sonarr.pfx'
        test_file: '/data/sonarr/config/sonarr.pfx'
        test_owner: '{{ omit }}'
        test_group: '{{ omit }}'
        test_mode: '{{ omit }}'
        test_state: 'absent'
        test_diff: true
