---
- name: 'Live API test | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Live API test | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Live API test | verify | query config.xml'
      ansible.builtin.copy:
        src: 'files/config.xml'
        dest: '/var/lib/sonarr/config.xml'
        owner: 'media'
        group: 'media'
        mode: '0600'
      check_mode: true
      diff: true
      register: _test_sonarr_config_xml

    - name: 'Live API test | verify | assert config.xml'
      ansible.builtin.assert:
        that:
          - not _test_sonarr_config_xml.changed
        fail_msg: >
          /var/lib/sonarr/config.xml is not in expected format:
          {{ _test_sonarr_config_xml.diff }}.

    # Sonarr will fail if configuration is bad (r_pufky.srv.systemd)
    - name: 'Live API test | verify | assert sonarr.service active'
      ansible.builtin.assert:
        that:
          - '"sonarr.service" in ansible_facts.services'
          - 'ansible_facts["services"]["sonarr.service"]["state"] == "running"'
        fail_msg: 'sonarr.service should be enabled and running.'

    - name: 'Live API test | verify | query /var/lib/sonarr'
      ansible.builtin.file:
        path: '/var/lib/sonarr'
        owner: 'media'
        group: 'media'
        mode: '0775'
      check_mode: true
      diff: true
      register: _test_sonarr_var_lib

    - name: 'Live API test | verify | assert /var/lib/sonarr'
      ansible.builtin.assert:
        that:
          - not _test_sonarr_var_lib.changed
        fail_msg: >
          /var/lib/sonarr should exist as 0775 media:media
          ({{ _test_sonarr_var_lib.diff }}).

    - name: 'Live API test | verify | query /var/lib/sonarr/update_script'
      ansible.builtin.file:
        path: '/var/lib/sonarr/update_script'
        state: 'absent'
      check_mode: true
      register: _test_sonarr_update

    - name: 'Live API test | verify | assert /var/lib/sonarr/update_script'
      ansible.builtin.assert:
        that:
          - not _test_sonarr_update.changed
        fail_msg: '/var/lib/sonarr/update_script should not exist.'

    - name: 'Live API test | verify | query /var/lib/sonarr/sonarr.pfx'
      ansible.builtin.file:
        path: '/var/lib/sonarr/sonarr.pfx'
        state: 'absent'
      check_mode: true
      register: _test_sonarr_pfx

    - name: 'Live API test | verify | assert /var/lib/sonarr/sonarr.pfx'
      ansible.builtin.assert:
        that:
          - not _test_sonarr_pfx.changed
        fail_msg: '/var/lib/sonarr/sonarr.pfx should not exist.'

    - name: 'Live API test | verify | query /data/media'
      ansible.builtin.file:
        path: '/data/media'
        owner: 'media'
        group: 'media'
        mode: '0755'
      check_mode: true
      diff: true
      register: _test_sonarr_data_media

    - name: 'Live API test | verify | assert /data/media'
      ansible.builtin.assert:
        that:
          - not _test_sonarr_data_media.changed
        fail_msg: >
          /data/media should exist as 0755 media:media
          ({{ _test_sonarr_data_media.diff }}).
