---
# yamllint disable rule:line-length
###############################################################################
# Annotate User Configuration
###############################################################################
# Sanitize (standardize with default values if not set) Sonarr configuration.
#
# Sonarr does not consistently apply casing to XML settings and are frequently
# mis-spelled, inconsistently spelled, ordered, or strings used for boolean
# values; so we have to explicitly map those settings to the equivalent role
# settings. Order does not matter but will change based on WebUI usage and what
# values were changed last. This can lead to 'changed' configurations when no
# values were actually changed.
#
# A necessary evil given the limitations of argument_spec:
# * Strong validation and sanitization of user input.
# * Annotated variable providing context and rendering hints.
# * Logic updates centrally located in tasks.
# * Simplified role updates for variable changes.
# * All data touched by user is in a standard, expected format.
#
# Annotated Defaults:
# _{VAR}: dict - Annotated and sanitized default variable.
#   section: str - Section name.
#   key: str - Config file key.
#   raw: any - Raw config file value (set from defaults > role defaults).
#   parsed: any - Processed raw config file value. Optional.
#   role: any - Role specific config usage. Optional.
#   hint: str - Value rendering type hint (docstring types).
#   added: str - Release version variable added.
#       Special Case:
#         0.0.0: Unknown or since role inception.
#   sensitive: bool - True for PII/SPII data that should not be logged.
#   deprecated: bool - True if no longer used in current role release.
#   order: int - Order item should appear in rendered files.
#
# Generates:
#   _sonarr_map: list of dict - Annotated config map.
#   _sonarr_order: list of str - Config section order.
#
# Reference:
# * https://sonarr.audio/
# * https://wiki.servarr.com/sonarr
# * https://github.com/Sonarr/Sonarr/releases
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh
# yamllint enable rule:line-length

# TODO(4.0+): Remove variable renaming check on next major Sonarr release.
- name: 'Annotate | check deprecated variable usage'
  when: >
    hostvars[inventory_hostname] | dict2items |
    selectattr("key", "match", "sonarr_config_*") | length > 0 or
    hostvars[inventory_hostname] | dict2items |
    selectattr("key", "match", "sonarr_service_*") | length > 0
  ansible.builtin.fail:
    msg: |
      ✘ Role variables have migrated. Read defaults and update.

      sonarr_config_* -> sonarr_cfg_*
      sonarr_service_* -> sonarr_srv_*
      sonarr_* -> sonarr_srv_*

- name: 'Annotate | sanitize & annotate service defaults'
  ansible.builtin.set_fact:
    _sonarr_srv_version: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_version | default(sonarr_role_validate_version) }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _sonarr_srv_delete_old_versions_enable: {
      section: '',
      key: '',
      raw: '{{
        sonarr_srv_delete_old_versions_enable | default(true)
      }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _sonarr_srv_config_dir: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_config_dir | default("/data/sonarr/config") }}',
      parsed: '{{
        sonarr_srv_config_dir | default("/data/sonarr/config")
        if
        (sonarr_srv_config_dir | default("/data/sonarr/config")).endswith("/")
        else
        sonarr_srv_config_dir | default("/data/sonarr/config") ~ "/"
      }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _sonarr_srv_u_mask: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_u_mask | default("0002") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 4,
    }
    _sonarr_srv_force_overwrite: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_force_overwrite | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 5,
    }
    _sonarr_srv_migrate_metadata: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_migrate_metadata | default(true) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 6,
    }
    _sonarr_srv_permissions_recursive_enable: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_permissions_recursive_enable | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 7,
    }
    _sonarr_srv_restart_daily_enable: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_restart_daily_enable | default(true) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 8,
    }
    _sonarr_srv_force_config_only_enable: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_force_config_only_enable | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 9,
    }
    _sonarr_srv_user: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_user | default("media") }}',
      parsed: '',  # Updated with UID when determined in prep.
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 10,
    }
    _sonarr_srv_group: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_group | default("media") }}',
      parsed: '',  # Updated with UID when determined in prep.
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 11,
    }
    _sonarr_srv_create_user: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_create_user | default(true) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 12,
    }
    _sonarr_srv_media_root_folders: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_media_root_folders | default([]) }}',
      hint: 'list of str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 13,
    }
    _sonarr_srv_user_data_manage_enable: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_user_data_manage_enable | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 14,
    }
    _sonarr_srv_media_perms_folder: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_media_perms_folder | default("0755") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 15,
    }
    _sonarr_srv_media_set_perms_file_enable: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_media_set_perms_file_enable | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 16,
    }
    _sonarr_srv_media_perms_file: {
      section: '',
      key: '',
      raw: '{{ sonarr_srv_media_perms_file | default("0644") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 17,
    }

- name: 'Annotate | sanitize & annotate config defaults'
  ansible.builtin.set_fact:
    _sonarr_cfg_bind_address: {
      section: 'General',
      key: 'BindAddress',
      raw: '{{ sonarr_cfg_bind_address | default("*") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }
    _sonarr_cfg_port: {
      section: 'General',
      key: 'Port',
      raw: '{{ sonarr_cfg_port | default(8989) }}',
      hint: 'int',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 2,
    }
    _sonarr_cfg_url_base: {
      section: 'General',
      key: 'UrlBase',
      raw: '{{ sonarr_cfg_url_base | default("") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 3,
    }
    _sonarr_cfg_instance_name: {
      section: 'General',
      key: 'InstanceName',
      raw: '{{ sonarr_cfg_instance_name | default("Sonarr") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 4,
    }
    _sonarr_cfg_enable_ssl: {
      section: 'General',
      key: 'EnableSsl',
      raw: '{{ sonarr_cfg_enable_ssl | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 5,
    }
    _sonarr_cfg_ssl_port: {
      section: 'General',
      key: 'SslPort',
      raw: '{{ sonarr_cfg_ssl_port | default(9898) }}',
      hint: 'int',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 6,
    }
    _sonarr_cfg_ssl_cert_path: {
      section: 'General',
      key: 'SslCertPath',
      raw: '{{ sonarr_cfg_ssl_cert_path | default("") }}',
      parsed: '',  # Updated after initial set.
      role: '',  # Updated after initial set.
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 7,
    }
    _sonarr_cfg_ssl_cert_password: {
      section: 'General',
      key: 'SslCertPassword',
      raw: '{{ sonarr_cfg_ssl_cert_password | default("") }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 8,
    }
    # TODO(V4): sonarr_cfg_authentication_method switches from 'none' to
    #     'external' on V4 codebase sync.
    _sonarr_cfg_authentication_method: {
      section: 'General',
      key: 'AuthenticationMethod',
      raw: '{{
          sonarr_cfg_authentication_method | default("Forms") | capitalize
      }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 9,
    }
    _sonarr_cfg_authentication_required: {
      section: 'General',
      key: 'AuthenticationRequired',
      raw: '{{ sonarr_cfg_authentication_required | default(false) }}',
      parsed: '{{
          "Enabled"
          if sonarr_cfg_authentication_required | default(false) else
          "DisabledForLocalAddresses"
      }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 10,
    }
    _sonarr_cfg_api_key: {
      section: 'General',
      key: 'ApiKey',
      raw: '{{
          sonarr_cfg_api_key |
          default(inventory_hostname | md5 | truncate(32, true, ""))
      }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: true,
      deprecated: false,
      order: 11,
    }
    _sonarr_cfg_log_level: {
      section: 'General',
      key: 'LogLevel',
      raw: '{{ sonarr_cfg_log_level | default("info") | lower }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 12,
    }
    _sonarr_cfg_log_size_limit: {
      section: 'General',
      key: 'LogSizeLimit',
      raw: '{{ sonarr_cfg_log_size_limit | default(1) }}',
      hint: 'int',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 13,
    }
    _sonarr_cfg_analytics_enabled: {
      section: 'General',
      key: 'AnalyticsEnabled',
      raw: '{{ sonarr_cfg_analytics_enabled | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 14,
    }
    _sonarr_cfg_branch: {
      section: 'General',
      key: 'Branch',
      raw: '{{ sonarr_cfg_branch | default("main") | lower }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 15,
    }
    _sonarr_cfg_update_automatically: {
      section: 'General',
      key: 'UpdateAutomatically',
      raw: '{{ sonarr_cfg_update_automatically | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 16,
    }
    _sonarr_cfg_update_mechanism: {
      section: 'General',
      key: 'UpdateMechanism',
      raw: '{{ sonarr_cfg_update_mechanism | default(true) }}',
      parsed: '{{
          "BuiltIn"
          if sonarr_cfg_update_mechanism | default(true) else
          "Script"
      }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 17,
    }
    _sonarr_cfg_update_script_path: {
      section: 'General',
      key: 'UpdateScriptPath',
      raw: '{{ sonarr_cfg_update_script_path | default("") }}',
      parsed: '',  # Updated after initial set.
      role: '',  # Updated after initial set.
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 18,
    }
    _sonarr_cfg_launch_browser: {
      section: 'General',
      key: 'LaunchBrowser',
      raw: '{{ sonarr_cfg_launch_browser | default(false) }}',
      hint: 'bool',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 19,
    }
    _sonarr_cfg_theme: {
      section: 'UI',
      key: 'Theme',
      raw: '{{ sonarr_cfg_theme | default("auto") | lower }}',
      hint: 'str',
      added: '0.0.0',
      sensitive: false,
      deprecated: false,
      order: 1,
    }

- name: 'Annotate | update annotations with results'
  ansible.builtin.set_fact:
    _sonarr_cfg_ssl_cert_path: '{{
      _sonarr_cfg_ssl_cert_path |
      combine({"parsed":
          _sonarr_srv_config_dir.parsed ~ "sonarr.pfx"
          if _sonarr_cfg_enable_ssl.raw else
          ""
        })
      }}'
    _sonarr_cfg_update_script_path: '{{
      _sonarr_cfg_update_script_path |
      combine({"parsed":
          _sonarr_srv_config_dir.parsed ~ "update_script"
          if not _sonarr_cfg_update_mechanism.raw else
          ""
        })
      }}'

- name: 'Annotate | generate role settings'
  ansible.builtin.set_fact:
    _sonarr_srv_migrate_metadata: '{{
      _sonarr_srv_migrate_metadata |
      combine({"role":
          sonarr_role_repo_extract_migrate_files
          if not _sonarr_srv_migrate_metadata.raw else
          sonarr_role_repo_extract_migrate_files + ["MediaCover"]})
        }}'
    _sonarr_cfg_ssl_cert_path: '{{
        _sonarr_cfg_ssl_cert_path |
        combine({"role": _sonarr_srv_config_dir.parsed ~ "sonarr.pfx"})
      }}'
    _sonarr_cfg_update_script_path: '{{
        _sonarr_cfg_update_script_path |
        combine({"role": _sonarr_srv_config_dir.parsed ~ "update_script"})
      }}'

- name: 'Annotate | generate config map'
  ansible.builtin.set_fact:
    _sonarr_map: '{{
        hostvars[inventory_hostname] | dict2items |
        selectattr("key", "match", "_sonarr_cfg_*")
      }}'
    _sonarr_order:
      - 'General'
      - 'UI'
