---
# yamllint disable rule:line-length
###############################################################################
# Annotate User Configuration
###############################################################################
# Sanitize (standardize with default values if not set) Sonarr configuration.
#
# Sonarr does not consistently apply casing to XML settings and are frequently
# mis-spelled, inconsistently spelled, ordered, or strings used for boolean
# values; so we have to explicitly map those settings to the equivalent role
# settings. Order does not matter but will change based on WebUI usage and what
# values were changed last. This can lead to 'changed' configurations when no
# values were actually changed.
#
# Use r_pufky.data.v3 data annotations to enforce consistency and validation
# checks.
#
# Generates:
#   _sonarr_map: list of dict - Annotated config map.
#   _sonarr_order: list of str - Config section order.
#
# Reference:
# * https://sonarr.audio/
# * https://wiki.servarr.com/sonarr
# * https://github.com/Sonarr/Sonarr/releases
# * https://github.com/Servarr/Wiki/blob/master/servarr/servarr-install-script.sh
# yamllint enable rule:line-length

- name: 'Annotate | sanitize & annotate service defaults'
  ansible.builtin.set_fact:  # noqa jinja[spacing] readability.
    _sonarr_srv_version: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_version,
        default=sonarr_role_validate_version,
        hint='str',
        order=1
        )
      }}"
    _sonarr_srv_delete_old_versions_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_delete_old_versions_enable,
        default=true,
        hint='bool',
        order=2
        )
      }}"
    _sonarr_srv_config_dir: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_config_dir,
        data=sonarr_srv_config_dir | regex_replace('\\/$', '') ~ '/',
        default='/data/sonarr/config',
        hint='str',
        order=3
        )
      }}"
    _sonarr_srv_u_mask: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_u_mask,
        default='0002',
        hint='str',
        order=4
        )
      }}"
    _sonarr_srv_force_overwrite: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_force_overwrite,
        default=false,
        hint='bool',
        order=5
        )
      }}"
    _sonarr_srv_migrate_metadata: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_migrate_metadata,
        _files=(
          sonarr_role_repo_extract_migrate_files
          if not sonarr_srv_migrate_metadata else
          sonarr_role_repo_extract_migrate_files + ['MediaCover']
        ),
        default=true,
        hint='bool',
        order=6
        )
      }}"
    _sonarr_srv_permissions_recursive_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_permissions_recursive_enable,
        default=false,
        hint='bool',
        order=7
        )
      }}"
    _sonarr_srv_restart_daily_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_restart_daily_enable,
        default=true,
        hint='bool',
        order=8
        )
      }}"
    _sonarr_srv_force_config_only_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_force_config_only_enable,
        default=true,
        hint='bool',
        order=9
        )
      }}"
    _sonarr_srv_user: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_user,
        default='media',
        hint='str',
        _uid='',
        order=10
        )
      }}"
    _sonarr_srv_group: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_group,
        default='media',
        hint='str',
        _gid='',
        order=11
        )
      }}"
    _sonarr_srv_create_user: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_create_user,
        default=true,
        hint='bool',
        order=12
        )
      }}"
    _sonarr_srv_media_root_folders: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_media_root_folders,
        default=[],
        hint='list of str',
        order=13
        )
      }}"
    _sonarr_srv_user_data_manage_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_user_data_manage_enable,
        default=false,
        hint='bool',
        order=14
        )
      }}"
    _sonarr_srv_media_perms_folder: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_media_perms_folder,
        default='0755',
        hint='str',
        order=15
        )
      }}"
    _sonarr_srv_media_set_perms_file_enable: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_media_set_perms_file_enable,
        default=false,
        hint='bool',
        order=16
        )
      }}"
    _sonarr_srv_media_perms_file: "{{ {} | r_pufky.data.v3(
        raw=sonarr_srv_media_perms_file,
        default='0644',
        hint='str',
        order=17
        )
      }}"

- name: 'Annotate | sanitize & annotate config defaults'
  ansible.builtin.set_fact:  # noqa jinja[spacing] readability.
    _sonarr_cfg_bind_address: "{{ {} | r_pufky.data.v3(
        section='General',
        key='BindAddress',
        raw=sonarr_cfg_bind_address,
        default='*',
        hint='str',
        order=1
        )
      }}"
    _sonarr_cfg_port: "{{ {} | r_pufky.data.v3(
        section='General',
        key='Port',
        raw=sonarr_cfg_port,
        default=8989,
        hint='int',
        order=2
        )
      }}"
    _sonarr_cfg_url_base: "{{ {} | r_pufky.data.v3(
        section='General',
        key='UrlBase',
        raw=sonarr_cfg_url_base,
        default='',
        hint='str',
        order=3
        )
      }}"
    _sonarr_cfg_instance_name: "{{ {} | r_pufky.data.v3(
        section='General',
        key='InstanceName',
        raw=sonarr_cfg_instance_name,
        default='Sonarr',
        hint='str',
        order=4
        )
      }}"
    _sonarr_cfg_enable_ssl: "{{ {} | r_pufky.data.v3(
        section='General',
        key='EnableSsl',
        raw=sonarr_cfg_enable_ssl,
        default=false,
        hint='bool',
        order=5
        )
      }}"
    _sonarr_cfg_ssl_port: "{{ {} | r_pufky.data.v3(
        section='General',
        key='SslPort',
        raw=sonarr_cfg_ssl_port,
        default=9898,
        hint='int',
        order=6
        )
      }}"
    _sonarr_cfg_ssl_cert_path: "{{ {} | r_pufky.data.v3(
        section='General',
        key='SslCertPath',
        raw=sonarr_cfg_ssl_cert_path,
        data=(
          _sonarr_srv_config_dir.data ~ 'sonarr.pfx'
          if sonarr_cfg_enable_ssl else
          ''
        ),
        default='',
        _dest=_sonarr_srv_config_dir.data ~ 'sonarr.pfx',
        hint='str',
        order=7
        )
      }}"
    _sonarr_cfg_ssl_cert_password: "{{ {} | r_pufky.data.v3(
        section='General',
        key='SslCertPassword',
        raw=sonarr_cfg_ssl_cert_password,
        default='',
        hint='str',
        sensitive=true,
        order=8
        )
      }}"
    # TODO(V4): sonarr_cfg_authentication_method switches from 'none' to
    #     'external' on V4 codebase sync.
    _sonarr_cfg_authentication_method: "{{ {} | r_pufky.data.v3(
        section='General',
        key='AuthenticationMethod',
        raw=sonarr_cfg_authentication_method | capitalize,
        default='Forms',
        hint='str',
        order=9
        )
      }}"
    _sonarr_cfg_authentication_required: "{{ {} | r_pufky.data.v3(
        section='General',
        key='AuthenticationRequired',
        raw=sonarr_cfg_authentication_required,
        data=(
          'Enabled'
          if sonarr_cfg_authentication_required else
          'DisabledForLocalAddresses'
        ),
        default=false,
        hint='str',
        order=10
        )
      }}"
    _sonarr_cfg_api_key: "{{ {} | r_pufky.data.v3(
        section='General',
        key='ApiKey',
        raw=sonarr_cfg_api_key,
        default=inventory_hostname | md5 | truncate(32, true, ''),
        hint='str',
        sensitive=true,
        order=11
        )
      }}"
    _sonarr_cfg_log_level: "{{ {} | r_pufky.data.v3(
        section='General',
        key='LogLevel',
        raw=sonarr_cfg_log_level | lower,
        default='info',
        hint='str',
        order=12
        )
      }}"
    _sonarr_cfg_log_size_limit: "{{ {} | r_pufky.data.v3(
        section='General',
        key='LogSizeLimit',
        raw=sonarr_cfg_log_size_limit,
        default=1,
        hint='int',
        order=13
        )
      }}"
    _sonarr_cfg_analytics_enabled: "{{ {} | r_pufky.data.v3(
        section='General',
        key='AnalyticsEnabled',
        raw=sonarr_cfg_analytics_enabled,
        default=false,
        hint='bool',
        order=14
        )
      }}"
    _sonarr_cfg_branch: "{{ {} | r_pufky.data.v3(
        section='General',
        key='Branch',
        raw=sonarr_cfg_branch | lower,
        default='main',
        hint='str',
        order=15
        )
      }}"
    _sonarr_cfg_update_automatically: "{{ {} | r_pufky.data.v3(
        section='General',
        key='UpdateAutomatically',
        raw=sonarr_cfg_update_automatically,
        default=false,
        hint='bool',
        order=16
        )
      }}"
    _sonarr_cfg_update_mechanism: "{{ {} | r_pufky.data.v3(
        section='General',
        key='UpdateMechanism',
        raw=sonarr_cfg_update_mechanism,
        data=(
          'BuiltIn'
          if sonarr_cfg_update_mechanism else
          'Script'
        ),
        default=true,
        hint='bool',
        order=17
        )
      }}"
    _sonarr_cfg_update_script_path: "{{ {} | r_pufky.data.v3(
        section='General',
        key='UpdateScriptPath',
        raw=sonarr_cfg_update_script_path,
        data=(
          _sonarr_srv_config_dir.data ~ 'update_script'
          if not sonarr_cfg_update_mechanism else
          ''
        ),
        default='',
        _dest=_sonarr_srv_config_dir.data ~ 'update_script',
        hint='str',
        order=18
        )
      }}"
    _sonarr_cfg_launch_browser: "{{ {} | r_pufky.data.v3(
        section='General',
        key='LaunchBrowser',
        raw=sonarr_cfg_launch_browser,
        default=false,
        hint='bool',
        order=19
        )
      }}"
    _sonarr_cfg_database_type: "{{ {} | r_pufky.data.v3(
        section='database',
        raw=sonarr_cfg_database_type | lower,
        default='sqlite',
        keep=false,
        hint='str',
        added='4.0.0',
        comment='Never set in config.xml.',
        order=1
        )
      }}"
    _sonarr_cfg_database_host: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresHost',
        raw=sonarr_cfg_database_host,
        default='localhost',
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='str',
        added='4.0.0',
        order=2
        )
      }}"
    _sonarr_cfg_database_port: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresPort',
        raw=sonarr_cfg_database_port,
        default=5432,
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='int',
        added='4.0.0',
        order=3
        )
      }}"
    _sonarr_cfg_database_user: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresUser',
        raw=sonarr_cfg_database_user,
        default='sonarr',
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='str',
        added='4.0.0',
        order=4
        )
      }}"
    _sonarr_cfg_database_password: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresPassword',
        raw=sonarr_cfg_database_password,
        default='',
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='str',
        added='4.0.0',
        sensitive=true,
        order=5
        )
      }}"
    _sonarr_cfg_database_main: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresMainDb',
        raw=sonarr_cfg_database_main,
        default='sonarr-main',
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='str',
        added='4.0.0',
        order=6
        )
      }}"
    _sonarr_cfg_database_log: "{{ {} | r_pufky.data.v3(
        section='database',
        key='PostgresLogDb',
        raw=sonarr_cfg_database_log,
        default='sonarr-log',
        keep=false if sonarr_cfg_database_type == 'sqlite' else true,
        hint='str',
        added='4.0.0',
        order=7
        )
      }}"
    _sonarr_cfg_theme: "{{ {} | r_pufky.data.v3(
        section='UI',
        key='Theme',
        raw=sonarr_cfg_theme | lower,
        default='auto',
        hint='str',
        order=1
        )
      }}"

- name: 'Annotate | generate config map'
  ansible.builtin.set_fact:
    _sonarr_map: '{{
        hostvars[inventory_hostname] | dict2items |
        selectattr("key", "match", "_sonarr_cfg_*")
      }}'
    _sonarr_order:
      - 'General'
      - 'database'
      - 'UI'
