---
###############################################################################
# Configure Services
###############################################################################
# Filetree returns a dict (instead of a list of dict) for one element. Use
# query to guarantee a list result.
#
# MediaCover (metadata) directory is Multi-GB. Safe to delete but will cause
# large metadata downloads on new version if not migrated with databases.
# Exclude from removal during configuration sync.

- name: 'Config | filetree | deploy managed files'
  ansible.builtin.template:
    src: '{{ item.src }}'
    dest: '{{ sonarr__cfg._var_dir ~ "/" ~ item.path }}'
    owner: '{{ sonarr__srv._user }}'
    group: '{{ sonarr__srv._group }}'
    mode: '0640'
  loop: '{{ query("community.general.filetree", sonarr__cfg._dir) }}'
  loop_control:
    label: '{{ item.path }}'
  when: item.state == 'file'
  register: sonarr__local

- name: 'Config | filesystem | query remote files'
  ansible.builtin.find:
    paths: '{{ sonarr__cfg._var_dir }}'
    file_type: 'file'
    recurse: true
    excludes: 'MediaCover'  # Ignore MediaCover to prevent metadata deletion.
  register: sonarr__remote

- name: 'Config | filesystem | remove unmanaged files'
  ansible.builtin.file:
    path: '{{ item.path }}'
    state: 'absent'
  loop: '{{ sonarr__remote.files }}'
  loop_control:
    label: '{{ item.path }}'
  when: >
    item.path not in sonarr__local.results | map(attribute='dest') | list
