---
# yamllint disable rule:line-length
###############################################################################
# Sonarr Config
###############################################################################
# Sonarr is installed from source. Create systemd service and reload daemons,
# create required directories, certificates, set config, and start service.
# Service may not exist if first install.
#
# Reference:
# * https://github.com/Sonarr/Sonarr/blob/develop/distribution/debian/install.sh
# * https://github.com/Sonarr/Sonarr/blob/main/distribution/debian/sonarr.service
# yamllint enable rule:line-length

- name: 'Config | set {{ _sonarr_srv_config_dir.raw }}'
  ansible.builtin.file:
    path: '{{ _sonarr_srv_config_dir.raw }}'
    owner: '{{ _sonarr_srv_user.raw }}'
    group: '{{ _sonarr_srv_group.raw }}'
    mode: '0775'
    recurse: '{{ _sonarr_srv_permissions_recursive_enable.raw }}'
    state: 'directory'
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _sonarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _sonarr_srv_user.raw
      if _sonarr_srv_user_data_manage_enable.raw else
      omit
    }}'

- name: 'Config | set {{ _sonarr_cfg_ssl_cert_path.parsed }}'
  when: _sonarr_cfg_enable_ssl.raw
  ansible.builtin.copy:
    src: '{{ _sonarr_cfg_ssl_cert_path.raw }}'
    dest: '{{ _sonarr_cfg_ssl_cert_path.parsed }}'
    owner: '{{ _sonarr_srv_user.parsed }}'
    group: '{{ _sonarr_srv_group.parsed }}'
    mode: '0640'
    force: true

- name: 'Config | remove {{ _sonarr_cfg_ssl_cert_path.role }}'
  when: not _sonarr_cfg_enable_ssl.raw
  ansible.builtin.file:
    dest: '{{ _sonarr_cfg_ssl_cert_path.role }}'
    state: 'absent'

- name: 'Config | set {{ _sonarr_cfg_update_script_path.parsed }}'
  when: not _sonarr_cfg_update_mechanism.raw
  ansible.builtin.copy:
    src: '{{ _sonarr_cfg_update_script_path.raw }}'
    dest: '{{ _sonarr_cfg_update_script_path.parsed }}'
    owner: '{{ _sonarr_srv_user.parsed }}'
    group: '{{ _sonarr_srv_group.parsed }}'
    mode: '0750'
    force: true

- name: 'Config | remove {{ _sonarr_cfg_update_script_path.role }}'
  when: _sonarr_cfg_update_mechanism.raw
  ansible.builtin.file:
    dest: '{{ _sonarr_cfg_update_script_path.role }}'
    state: 'absent'

- name: 'Config | set media root folders'
  ansible.builtin.file:
    path: '{{ item }}'
    owner: '{{ _sonarr_srv_user.parsed }}'
    group: '{{ _sonarr_srv_group.parsed }}'
    mode: '{{ _sonarr_srv_media_perms_folder.raw }}'
    recurse: '{{ _sonarr_srv_permissions_recursive_enable.raw }}'
    state: 'directory'
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _sonarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _sonarr_srv_user.raw
      if _sonarr_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop: '{{ _sonarr_srv_media_root_folders.raw }}'

- name: 'Config | set media root files'
  when: _sonarr_srv_media_set_perms_file_enable.raw
  ansible.builtin.shell: >-
    find '{{ item }}'
    -type f
    -exec chmod {{ _sonarr_srv_media_perms_file.raw }} {};
      chown {{ _sonarr_srv_user.parsed }}:{{ _sonarr_srv_group.parsed }} {} \;
  changed_when: false  # https://github.com/ansible/ansible/issues/32636
  become:
    '{{ true if _sonarr_srv_user_data_manage_enable.raw else omit }}'
  become_user: '{{
      _sonarr_srv_user.raw
      if _sonarr_srv_user_data_manage_enable.raw else
      omit
    }}'
  loop: '{{ _sonarr_srv_media_root_folders.raw }}'

# Writing the configuration back requires to_json, ansible.utils.to_xml, and
# xmltodict python3 package installed on both controller and node. Just use a
# template instead with datatype rendering hints.
- name: 'Config | set Sonarr configuration'
  ansible.builtin.template:
    src: 'config.xml.j2'
    dest: '{{ _sonarr_srv_config_dir.parsed ~ "config.xml" }}'
    owner: '{{ _sonarr_srv_user.parsed }}'
    group: '{{ _sonarr_srv_group.parsed }}'
    mode: '0600'

- name: 'Config | Sonarr service'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.systemd'
  vars:
    systemd_daemon_reload_enable: true
    systemd_services:
      - name: 'sonarr'
        state: 'present'
        drop_in: false
        unit:
          description: 'Sonarr Daemon'
          after:
            - 'syslog.target'
            - 'network.target'
        service:
          type: 'simple'
          exec_start:
            - >-
              {{ sonarr_role_repo_extract_symlink ~ "/Sonarr" }}
              -nobrowser
              -data={{ _sonarr_srv_config_dir.raw }}
          timeout_stop_sec: 20
          restart: 'always'  # Always restart for periodic service restarts.
          runtime_max_sec: '{{
              "1d"
              if _sonarr_srv_restart_daily_enable.raw else
              "infinity"
            }}'
        exec:
          user: '{{ _sonarr_srv_user.raw }}'
          group: '{{ _sonarr_srv_group.raw }}'
          u_mask: '{{ _sonarr_srv_u_mask.raw }}'
        kill:
          kill_mode: 'process'
        install:
          wanted_by:
            - 'multi-user.target'
