---
###############################################################################
# Sonarr Install
###############################################################################
# Install specified version from github release.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ sonarr_role_packages }}'
    apt_package_update_cache: true

- name: 'Install | Sonarr package {{ _sonarr_srv_version.raw }}'
  when: not _sonarr_srv_force_config_only_enable.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.repo'
  vars:
    repo_release_owner: '{{ sonarr_role_repo_release_owner }}'
    repo_release_repo: '{{ sonarr_role_repo_release_repo }}'
    repo_release_tag: '{{ _sonarr_srv_version.raw }}'
    repo_release_specifier: '{{ sonarr_role_repo_release_specifier }}'
    repo_release_asset: '{{ sonarr_role_repo_release_asset }}'
    repo_file_owner: '{{ _sonarr_srv_user.role_uid }}'
    repo_file_group: '{{ _sonarr_srv_group.role_gid }}'
    repo_extract_dir: '{{ sonarr_role_repo_extract_dir }}'
    repo_extract_symlink: '{{ sonarr_role_repo_extract_symlink }}'
    repo_extract_migrate_files: '{{ _sonarr_srv_migrate_metadata.role_files }}'
    repo_extract_delete_old_versions:
      '{{ _sonarr_srv_delete_old_versions_enable.raw }}'
    repo_force_overwrite: '{{ _sonarr_srv_force_overwrite.raw }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_extra_opts: '--strip-components=1'
