---
# yamllint disable rule:line-length
###############################################################################
# Sonarr Install
###############################################################################
# Install specified version from github release.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ sonarr_role_packages }}'
    apt_package_update_cache: true

- name: 'Install | Sonarr package {{ sonarr_service_version }}'
  when: not sonarr_service_force_config_only_enable
  ansible.builtin.include_role:
    name: 'r_pufky.srv.github'
  vars:
    github_repo_owner: '{{ sonarr_role_github_owner }}'
    github_repo_repo: '{{ sonarr_role_github_repo }}'
    github_repo_release: '{{ sonarr_service_version }}'
    github_repo_archive_type: '{{ sonarr_role_github_repo_archive_type }}'
    github_file_owner: '{{ sonarr_user }}'
    github_file_group: '{{ sonarr_group }}'
    github_extract_dest: '{{ sonarr_role_github_extract_dest }}'
    github_extract_symlink_target: '{{ sonarr_role_github_extract_symlink_target }}'
    github_extract_migrate_files:
      - 'sonarr.db'
      - 'sonarr.db-shm'  # Sonarr never closes DB's correctly.
      - 'sonarr.db-wal'
      - 'logs.db'
      - 'logs.db-shm'
      - 'logs.db-wal'
    github_extract_delete_old_versions: '{{ sonarr_service_delete_old_versions_enable }}'
    github_force_overwrite: '{{ sonarr_service_force_overwrite }}'
    github_extract_mode: 'a-st,o-rwx'
    github_extract_extra_opts: '--strip-components=1'
