---
# yamllint disable rule:line-length
###############################################################################
# Sonarr Install
###############################################################################
# Install specified version from github release.
#
# Args:
#   _sonarr_migrate_metadata: list of str - files and directories to migrate.

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.srv.apt'
  vars:
    apt_packages:
      - '{{ sonarr_role_packages }}'
    apt_package_update_cache: true

- name: 'Install | Sonarr package {{ sonarr_service_version }}'
  when: not sonarr_service_force_config_only_enable
  ansible.builtin.include_role:
    name: 'r_pufky.srv.repo'
  vars:
    repo_release_owner: '{{ sonarr_role_repo_release_owner }}'
    repo_release_repo: '{{ sonarr_role_repo_release_repo }}'
    repo_release_tag: '{{ sonarr_service_version }}'
    repo_release_specifier: '{{ sonarr_role_repo_release_specifier }}'
    repo_release_asset: '{{ sonarr_role_repo_release_asset }}'
    repo_file_owner: '{{ sonarr_user }}'
    repo_file_group: '{{ sonarr_group }}'
    repo_extract_dir: '{{ sonarr_role_repo_extract_dir }}'
    repo_extract_symlink_target: '{{ sonarr_role_repo_extract_symlink_target }}'
    repo_extract_migrate_files: '{{ _sonarr_migrate_metadata }}'
    repo_extract_delete_old_versions: '{{ sonarr_service_delete_old_versions_enable }}'
    repo_force_overwrite: '{{ sonarr_service_force_overwrite }}'
    repo_extract_mode: 'a-st,o-rwx'
    repo_extract_extra_opts: '--strip-components=1'
