---
###############################################################################
#  Pre Execution Tasks
###############################################################################
# Only use data annotations in role after merging role, defaults, runtime data.
# Service may not exist if first install.
#
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | fact | record start time'
  ansible.builtin.set_fact:
    sonarr__srv: "{{ sonarr___release | r_pufky.data.v3(

        _start=now(utc=True, fmt='%Y-%m-%dT%H%M%S'),
        _user=sonarr_srv_user,
        _group=sonarr_srv_group,
      ) }}"
    sonarr__cfg: "{{ sonarr___app | r_pufky.data.v3(

        _version=sonarr_srv_version,
        _package='Sonarr.main.' ~ sonarr_srv_version[1:] ~ '.linux-x64.tar.gz',
        _app_d='/opt/sonarr/src/' ~ sonarr_srv_version,
        _url=(
          sonarr___repo_url ~ sonarr_srv_version ~ '/' ~
          'Sonarr.main.' ~ sonarr_srv_version[1:] ~ '.linux-x64.tar.gz'
        ),
        _d=sonarr_cfg_d | regex_replace('\\/$', ''),
        _backup_d=sonarr_cfg_backup_d | regex_replace('\\/$', ''),
        _backup_metadata=sonarr_cfg_backup_metadata,
      ) }}"

- name: 'Prep | assert | backup enabled and location defined'
  when: sonarr_flg_backup
  ansible.builtin.assert:
    quiet: true
    that:
      - sonarr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      sonarr_flg_backup: {{ sonarr_flg_backup }}
      sonarr_cfg_backup_d: {{ sonarr__cfg._backup_d }}

- name: 'Prep | assert | restore enabled and location defined'
  when: sonarr_flg_restore
  ansible.builtin.assert:
    quiet: true
    that:
      - sonarr__cfg._backup_d | length > 0
    fail_msg: |

      ✘ Backup location not set.
      Backups enabled but no backup location defined.

      sonarr_flg_restore: {{ sonarr_flg_restore }}
      sonarr_cfg_backup_d: {{ sonarr__cfg._backup_d }}

- name: 'Prep | assert | config enabled and source defined'
  when: sonarr_flg_config
  ansible.builtin.assert:
    quiet: true
    that:
      - sonarr__cfg._d | length > 0
    fail_msg: |

      ✘ Config source not set.
      Config source enabled but no config source defined.

      sonarr_flg_config: {{ sonarr_flg_config }}
      sonarr_cfg_d: {{ sonarr__cfg._d }}

- name: '{{ "Prep | account | query user " ~ sonarr__srv._user }}'
  ansible.builtin.command: '{{ "id " ~ sonarr__srv._user }}'
  failed_when: false
  register: sonarr__cfg_check
  changed_when: sonarr__cfg_check.rc > 0

- name: '{{ "Prep | account | query group " ~ sonarr__srv._group }}'
  ansible.builtin.command: '{{ "groups " ~ sonarr__srv._group }}'
  failed_when: false
  register: sonarr__group_check
  changed_when: sonarr__group_check.rc > 0

- name: '{{ "Prep | account | create group " ~ sonarr__srv._group }}'
  when: sonarr__group_check.rc != 0
  ansible.builtin.group:
    gid: '{{ sonarr___group.gid }}'
    name: '{{ sonarr___group.name }}'
    state: 'present'

- name: '{{ "Prep | account | create user " ~ sonarr__srv._user }}'
  when: sonarr__cfg_check.rc != 0
  ansible.builtin.user:
    name: '{{ sonarr___user.name }}'
    group: '{{ sonarr___user.group }}'
    uid: '{{ sonarr___user.uid }}'
    shell: '{{ sonarr___user.shell }}'
    home: '{{ sonarr___user.home }}'
    create_home: '{{ sonarr___user.create_home }}'
    password: '{{ sonarr___user.password }}'
    password_lock: '{{ sonarr___user.password_lock }}'
    update_password: '{{ sonarr___user.update_password }}'
    expires: '{{ sonarr___user.expires }}'
    system: '{{ sonarr___user.system }}'

# Pre-existing users may have a different UID/GID/Home.
- name: '{{ "Prep | account | enumerate " ~ sonarr__srv._user }}'
  ansible.builtin.user:
    name: '{{ sonarr__srv._user }}'
  check_mode: true
  changed_when: false
  register: sonarr__cfg_query

- name: 'Prep | fact | parse service UID/GID'
  ansible.builtin.set_fact:
    sonarr__cfg: "{{ sonarr__cfg | r_pufky.data.v3(

        _uid=sonarr__cfg_query.uid,
        _gid=sonarr__cfg_query.group,
      ) }}"

- name: 'Prep | systemd | stop sonarr.service'
  ansible.builtin.systemd:
    name: 'sonarr.service'
    state: 'stopped'
  failed_when: false
