---
###############################################################################
# Sonarr Prep
###############################################################################
# *arr services use the same codebase; any bugs or fixes should be checked for
# all related services.

- name: 'Prep | assert SSL requirements'
  when: _sonarr_cfg_enable_ssl.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _sonarr_cfg_ssl_cert_path.raw | length > 0
    fail_msg: >
      ✘ sonarr_cfg_enable_ssl=true requires
      sonarr_cfg_ssl_cert_path set.

      sonarr_cfg_ssl_cert_path: '{{ _sonarr_cfg_ssl_cert_path.raw }}'

- name: 'Prep | assert update script requirements'
  when: not _sonarr_cfg_update_mechanism.raw
  ansible.builtin.assert:
    quiet: true
    that:
      - _sonarr_cfg_update_script_path.raw | length > 0
    fail_msg: >
      ✘ sonarr_cfg_update_mechanism=false requires
      sonarr_cfg_update_script_path set.

      sonarr_cfg_update_script_path: '{{ _sonarr_cfg_update_script_path.raw }}'

- name: 'Prep | manage users'
  when: _sonarr_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ sonarr_role_user }}'
    users_role_group: '{{ sonarr_role_group }}'

- name: 'Prep | enumerate system user {{ _sonarr_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _sonarr_srv_user.raw }}'
  check_mode: true
  changed_when: false
  register: _sonarr_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _sonarr_srv_user: '{{
        _sonarr_srv_user |
        combine({"role_uid": _sonarr_srv_user_query.uid})
      }}'
    _sonarr_srv_group: '{{
        _sonarr_srv_group |
        combine({"role_gid": _sonarr_srv_user_query.group})
      }}'

- name: 'Prep | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'sonarr.service'
