---
###############################################################################
# Sonarr Handlers
###############################################################################

- name: 'restart sonarr'
  ansible.builtin.systemd:
    name:    'sonarr'
    enabled: true
    state:   'restarted'
