---
# yamllint disable rule:line-length
- name: 'Migrate V3 to V4 | prepare'
  hosts: 'all'
  gather_facts: false
  tags: 'molecule-idempotence-notest'
  tasks:
    - name: 'Migrate V3 to V4 | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'gnupg2'  # apt key management.
          - 'ca-certificates'  # SSL support for ansible.builtin.uri.
          - 'libicu67'  # unicode locale support for debian 11.
        update_cache: true
        state: 'present'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | create role account'
      ansible.builtin.include_role:
        name: 'r_pufky.srv.users'
        tasks_from: 'role_account_add'
      vars:
        users_role_user:
          name: '{{ sonarr_role_user.name }}'
          group: '{{ sonarr_role_user.group }}'
          uid: '{{ sonarr_role_user.uid }}'
          shell: '{{ sonarr_role_user.shell }}'
          home: '{{ sonarr_role_user.home }}'
          comment: '{{ sonarr_role_user.comment }}'
          create_home: '{{ sonarr_role_user.create_home }}'
          password: '{{ sonarr_role_user.password }}'
          password_lock: '{{ sonarr_role_user.password_lock }}'
          update_password: '{{ sonarr_role_user.update_password }}'
          expires: '{{ sonarr_role_user.expires }}'
          system: '{{ sonarr_role_user.system }}'
        users_role_group:
          name: '{{ sonarr_role_group.name }}'
          gid: '{{ sonarr_role_group.gid }}'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | add sonarr repo key'
      ansible.builtin.apt_key:
        keyserver: 'hkp://keyserver.ubuntu.com:80'
        id: '2009837CBFFD68F45BC180471F4F90DE2A9B4BF8'
        state: 'present'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | set version'
      ansible.builtin.set_fact:
        _sonarr_mono_version: 'stable-buster'
        _sonarr_repo: 'buster'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | add sonarr repo'
      ansible.builtin.apt_repository:
        repo: 'deb https://apt.sonarr.tv/debian buster main'
        filename: 'sonarr'
        state: 'present'
        update_cache: true

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | pre-configure sonarr group'
      ansible.builtin.debconf:
        name: 'sonarr'
        question: 'sonarr/owning_group'
        value: '{{ sonarr_group }}'
        vtype: 'string'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | pre-configure sonarr user'
      ansible.builtin.debconf:
        name: 'sonarr'
        question: 'sonarr/owning_user'
        value: '{{ sonarr_user }}'
        vtype: 'string'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | pre-configure sonarr directory'
      ansible.builtin.debconf:
        name: 'sonarr'
        question: 'sonarr/config_directory'
        value: '/var/lib/sonarr'
        vtype: 'string'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | install'
      ansible.builtin.apt:
        name: 'sonarr'
        state: 'present'
        update_cache: true

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | set configuration'
      ansible.builtin.template:
        src: 'templates/config_v3.xml.j2'
        dest: '/var/lib/sonarr/config.xml'
        owner: '{{ sonarr_user }}'
        group: '{{ sonarr_group }}'
        mode: '0600'

    - name: 'Migrate V3 to V4 | prepare | install sonarr v3 | restart V3 service'
      ansible.builtin.systemd:
        name: 'sonarr'
        enabled: true
        state: 'restarted'
        masked: false
