---
###############################################################################
# Sonarr Database Options
###############################################################################
# Existing databases are migrated automatically when new versions are
# installed. Migration between database platforms is not supported and must be
# done manually.

# Database backend.
#
# Values:
#   postgres: Postgres 14+. HIGHLY recommended.
#     sqlite: Sqlite3 (default).
#
# Default: 'sqlite'.
sonarr_cfg_database_type: 'sqlite'

###############################################################################
# PostgreSQL Database Options
###############################################################################
# Postgres requires pre-existing databases with root privileges to initialize
# tables and manage migrations. Postgres databases are NOT backed up by Sonarr.
#
# Manual Migration Overview:
# * Create postgres databases.
# * systemctl stop sonarr
# * sqlite3 sonarr.db vacuum
# * Update config.xml with DB settings (or re-apply role with postgres).
# * Confirm sonarr running (appears empty).
# * systemctl stop sonarr
# * cp sonarr.db postgres:/tmp
# * chmod o+r /tmp/sonarr.db
# * Install pgloader to /usr/local/bin
# * Login to postgres: psql -d sonarr
# * Remove auto-generated tables (see reference).
# * Execute pgloader. Use 'prefetch rows' and 'batch size' options.
#   * Many WARNINGS may appear; these can be ignored.
# * systemctl start sonarr
# * No migrations have needed post migration steps in practice.
# * Backup and remove sqlite3 database files.
#
# Reference:
# * https://wiki.servarr.com/en/sonarr/postgres-setup
# * https://github.com/Roxedus/Pgloader-bin

# Database host. Default: 'localhost'.
sonarr_cfg_database_host: 'localhost'

# Database port. Default: 5432.
sonarr_cfg_database_port: 5432

# Database user. Default: 'sonarr'.
sonarr_cfg_database_user: 'sonarr'

# Database password. Default: ''.
sonarr_cfg_database_password: ''

# Main database name. Default: 'sonarr-main'.
sonarr_cfg_database_main: 'sonarr-main'

# Log database name. Default: 'sonarr-log'.
sonarr_cfg_database_log: 'sonarr-log'
