---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    # Inject config.xml and reset DBs; config.xml tested after restore.
    - name: 'Converge | role | r_pufky.arr.sonarr (pre-configured config.xml)'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'
      vars:
        sonarr_flg_config: true
        sonarr_cfg_dir: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/files/default"
          }}'

    - name: 'Converge | role | r_pufky.arr.sonarr (create db backup)'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'
      vars:
        sonarr_flg_backup: true

    - name: 'Converge | role | r_pufky.arr.sonarr (restore)'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'
      vars:
        sonarr_flg_restore: true
