---
# yamllint disable rule:line-length
# Confirm:
# * config.xml set.
# * sonarr.service active and running.
# * /var/lib/sonarr created with correct permissions.
# * /data/media created with correct permissions.
# * /data/media - file permissions recursively set with correct permissions.
# * /var/lib/sonarr/update_script does not exist.
# * /var/lib/sonarr/sonarr.pfx does not exist.
dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        sonarr_media_root_folders: ['/data/media']
        sonarr_config_api_key: 'abcdef1234567890abcdef1234567890'
        github_testing_enable: true
        github_testing_versions:
          - 'v4.0.12.2823'
        github_testing_archives:
          - '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/files/Sonarr.main.4.0.12.2823.linux-x64.tar.gz'
platforms:
  - name: 'sonarr-debian-12-default'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    # - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
