---
###############################################################################
# Default
###############################################################################
# Default configuration is deployed successfully. Configuration should succeed
# with and without sonarr_srv_user_data_manage_enable.
#
# Tests:
# * files/default/config.xml set.
# * sonarr.service active and running.
# * Standard role run with auto generation (during prep).
# * Standard role run with injected config.xml.
# * Backup created.
# * Restore applied.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        url_inject_enable: true
        sonarr_cfg_backup_dir: '/tmp/ansible_sonarr_test'
        sonarr_cfg_backup_metadata: false
platforms:
  - name: 'sonarr-default'
    image: 'ghcr.io/hifis-net/debian-systemd:13'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
    published_ports:
      - '8989:8989/tcp'
verifier:
  name: 'ansible'
scenario:
  test_sequence:
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'verify'
    - 'destroy'
