---
- name: 'Prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Prepare | create cache'

    - name: 'Prepare | check cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Prepare | cache {{ item }}'
        test_dest: 'Sonarr.main.{{ item }}.linux-x64.tar.gz'
        test_url: '{{
            "https://github.com/Sonarr/Sonarr/releases/download/v" ~ item ~
            "/" ~ "Sonarr.main." ~ item ~ ".linux-x64.tar.gz"
          }}'
        test_mode: '0640'
      loop:
        - '4.0.8.1874'
        - '4.0.15.2941'

- name: 'Prepare'
  hosts: 'sonarr-debian-12-user_data'
  gather_facts: false
  tasks:
    - name: 'Prepare | simulate user media restriction'
      ansible.builtin.file:
        path: '/data'
        owner: 5555
        group: 5555
        mode: '0755'
        state: 'directory'
