---
- name: 'Default | prepare'
  hosts: 'all'
  gather_facts: false
  tags: 'molecule-idempotence-notest'
  tasks:
    - name: 'Default | prepare | base packages for bare-metal equivalency'
      ansible.builtin.apt:
        name:
          - 'ca-certificates'  # SSL support for ansible.builtin.uri.
          - 'libicu72'  # unicode locale support.
        update_cache: true
        state: 'present'
