---
- name: 'Default | prepare'
  hosts: 127.0.0.1
  connection: local
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'create_cache.yml'
      vars:
        test_name: 'Default | prepare | create cache'

    - name: 'Default | prepare | check cache'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'cache_url.yml'
      vars:
        test_name: 'Default | prepare | cache {{ item }}'
        test_dest: 'Sonarr.main.{{ item }}.linux-x64.tar.gz'
        test_url: '{{
            "https://github.com/Sonarr/Sonarr/releases/download/v" ~ item ~
            "/" ~ "Sonarr.main." ~ item ~ ".linux-x64.tar.gz"
          }}'
        test_mode: '0640'
      loop:
        - '4.0.8.1874'
        - '4.0.12.2823'
