---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | apply r_pufky.arr.sonarr'
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'

- name: 'Converge | toggle updates'
  hosts: 'sonarr-debian-13-update_mechanisms-toggle'
  gather_facts: false
  tasks:
    - name: >-
        Converge | toggle updates |
        apply r_pufky.arr.sonarr
      ansible.builtin.include_role:
        name: 'r_pufky.arr.sonarr'
      vars:
        sonarr_cfg_update_mechanism: true
