---
# yamllint disable rule:line-length
###############################################################################
# Update Mechanisms
###############################################################################
# Verify update scripts are deployed and executed correctly.
#
# Tests:
# * /var/lib/sonarr/update_script exists.
# * toggling script update on, then off removes update_script.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        sonarr_config_update_mechanism: false
        sonarr_config_update_script_path: 'files/update.sh'
        sonarr_media_root_folders: ['/data/media']
        sonarr_config_api_key: 'abcdef1234567890abcdef1234567890'
        repo_testing_enable: true
        repo_testing_versions:
          - comment: 'default'
            version: 'v4.0.12.2823'
            asset: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/Sonarr.main.4.0.12.2823.linux-x64.tar.gz'
          - comment: 'toggle'
            version: 'v4.0.12.2823'
            asset: '{{ lookup("env", "MOLECULE_PROJECT_DIRECTORY") }}/molecule/cache/Sonarr.main.4.0.12.2823.linux-x64.tar.gz'
platforms:
  - name: 'sonarr-debian-12-update_mechanisms'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'sonarr-debian-12-update_mechanisms-toggle'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # Files created, extracted, created, deleted.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
